# tests/test_data.py

VALID_REPO_NAME = "myrepo123"
INVALID_REPO_NAME_KEYWORD = "mlops_repo"
INVALID_REPO_NAME_SPECIAL = "mlops_repo$"
EMPTY_REPO_NAME = ""

VALID_TRAIN_ACC = 0.85
VALID_INFER_ACC = 0.80

INVALID_TRAIN_ACC = 1.85
INVALID_INFER_ACC = 1.80
